<?php

namespace App\Entity;

use App\Entity\City;

class CityWithDistrict extends City
{

    public function __construct(string $name, string $county, private string $district)
    {
        parent::setName($name);
        parent::setCounty($county);
    }

    public function __toString(): string
    {
        return parent::__toString() . " de la région $this->district"; // TODO: Change the autogenerated stub
    }

}